### ISSUE TITLE
ajouter les informations de l'etage dans la legende pour l'export en image

### ISSUE THREAD

**Issue by pouyajoon** [pouyajoon/GeoPRails#69]

**Comment by ggojard** [comment]
Creer une box svg avec les informations de cartouche en bas a droite du plan, sous la forme d 'un tableau:
**Batiment**
**Etage**
- **information 1** : Valeur 1
- **information 2** : Valeur 2
- **information ...** : Valeur ...

**Comment by pouyajoon** [comment]
ok pour le moment
